In [1]:
import pandas as pd

In [2]:
dados = pd.read_excel(r'C:\Users\helis\OneDrive\Área de Trabalho\Física\SEM 02\Laboratório de Física 1 - Mecânica\03 - Experimento MU\Dados MU.xlsx')

In [3]:
dados

    Ti (s)
0     6.27
1     6.24
2     6.41
3     6.09
4     6.36
5     6.85
6     6.45
7     6.32
8     6.49
9     6.71
10    6.37
11    6.48
12    6.58
13    6.22
14    6.05
15    6.29
16    6.21
17    6.10
18    6.47
19    6.16
20    6.29
21    6.56
22    6.13
23    6.31
24    6.44
25    6.59
26    6.36
27    6.36
28    6.27
29    6.55

In [4]:
dados['Di'] = dados['Ti (s)'] - dados['Ti (s)'].mean()

In [5]:
dados['Di²'] = dados['Di'].pow(2)

In [6]:
somaT = dados['Ti (s)'].sum()

In [7]:
somaT

np.float64(190.98000000000005)

In [8]:
mediaT = dados['Ti (s)'].mean()

In [9]:
mediaT

np.float64(6.366000000000001)

In [10]:
somaDi2 = dados['Di²'].sum()

In [11]:
somaDi2

np.float64(1.01552)

In [12]:
desvpad = dados['Ti (s)'].std()

In [13]:
dados[dados['Di'] > 3*desvpad]

Empty DataFrame
Columns: [Ti (s), Di, Di²]
Index: []

In [31]:
ictzpad = desvpad/(30**(1/2))

In [32]:
ictzpad

0.03416525088179644

Incerteza Padrão: 0,0342 s
Média: 6,366 s
T = (6,3660 +- 0,0342)s

In [33]:
mediaT

np.float64(6.366000000000001)

In [29]:
veloc = 0.4/6.3660

In [30]:
veloc

0.06283380458686774

In [34]:
ictz_veloc = veloc*(ictzpad/mediaT)

In [35]:
ictz_veloc

np.float64(0.0003372184570480848)

Velocidade Média: (0,0628 +- 0,0003) m/s

In [37]:
desvpad

0.18713078590783178